const days = 86400;

const testCases = {
  exchange: [
    {
      errorMessage: "",
      initRateETH2USD: 200,
      initVolatility: 1,
      periodSecBeforeMaturity: 84 * days,
      strikePrice: 100,
      decimal: 8,
    },
    {
      errorMessage: "",
      initRateETH2USD: 201,
      initVolatility: 0.1,
      periodSecBeforeMaturity: 4 * days,
      strikePrice: 200,
      decimal: 8,
    },
    {
      errorMessage: "exchange rate is too small",
      initRateETH2USD: 199,
      initVolatility: 0.01,
      periodSecBeforeMaturity: 1 * days,
      strikePrice: 200, // > initRateETH2USD
      decimal: 8,
    },
    {
      errorMessage: "",
      initRateETH2USD: 300,
      initVolatility: 0.5,
      periodSecBeforeMaturity: 4 * days,
      strikePrice: 110,
      decimal: 8,
    },
    {
      errorMessage: "",
      initRateETH2USD: 250,
      initVolatility: 1.5,
      periodSecBeforeMaturity: 30 * days,
      strikePrice: 50,
      decimal: 8,
    },
    {
      errorMessage: "",
      initRateETH2USD: 400,
      initVolatility: 0.8,
      periodSecBeforeMaturity: 7 * days,
      strikePrice: 200,
      decimal: 8,
    },
    {
      errorMessage: "",
      initRateETH2USD: 150,
      initVolatility: 1,
      periodSecBeforeMaturity: 40 * days,
      strikePrice: 100,
      decimal: 8,
    },
    {
      errorMessage: "",
      initRateETH2USD: 150,
      initVolatility: 1,
      periodSecBeforeMaturity: 40 * days,
      strikePrice: 100,
      decimal: 9,
    },
    {
      errorMessage: "",
      initRateETH2USD: 150,
      initVolatility: 1,
      periodSecBeforeMaturity: 40 * days,
      strikePrice: 100,
      decimal: 7,
    },
    {
      errorMessage: "",
      initRateETH2USD: 150,
      initVolatility: 1,
      periodSecBeforeMaturity: 40 * days,
      strikePrice: 100,
      decimal: 4,
      erc20PriceE0: 123.456789,
    },
    {
      errorMessage: "oracle volatility should be between 0% and 1000%",
      initRateETH2USD: 300,
      initVolatility: 0, // oracle volatility should be between 0% and 1000%
      periodSecBeforeMaturity: 4 * days,
      strikePrice: 100,
      decimal: 8,
    },
    {
      errorMessage: "the bond maturity must be less than 12 weeks",
      initRateETH2USD: 300,
      initVolatility: 0.5,
      periodSecBeforeMaturity: 85 * days, // the bond maturity must be less than 12 weeks
      strikePrice: 100,
      decimal: 8,
    },
    {
      errorMessage: "the bond should not have expired",
      initRateETH2USD: 300,
      initVolatility: 0.5,
      periodSecBeforeMaturity: 4 * days,
      strikePrice: 100,
      decimal: 8,
      exchangeTimeUntilMaturity: -1 * days, // the bond should not have expired
    },
    {
      errorMessage: "",
      initRateETH2USD: 300,
      initVolatility: 0.5,
      periodSecBeforeMaturity: 4 * days,
      strikePrice: 200,
      decimal: 8,
      spread: -0.003,
    },
    {
      errorMessage: "",
      initRateETH2USD: 300,
      initVolatility: 0.5,
      periodSecBeforeMaturity: 4 * days,
      strikePrice: 200,
      decimal: 8,
      spread: 0.003,
    },
    {
      errorMessage: "",
      initRateETH2USD: 201,
      initVolatility: 0.8,
      periodSecBeforeMaturity: 4 * days,
      strikePrice: 200,
      decimal: 8,
      spread: 0.003,
    },
    {
      errorMessage: "",
      initRateETH2USD: 199,
      initVolatility: 0.8,
      periodSecBeforeMaturity: 14 * days,
      strikePrice: 200, // > initRateETH2USD
      decimal: 8,
      spread: 0.003,
    },
    {
      errorMessage: "",
      isPutOption: true,
      initRateETH2USD: 380,
      initVolatility: 0.8,
      periodSecBeforeMaturity: 14 * days,
      strikePrice: 1 / 400,
      erc20PriceE0: 1,
      decimal: 6,
      spread: 0,
      callOptionApproximation: 35.64268169 / 400 / 380,
      callOptionApproximationAccuracy: 0.95,
    },
    {
      errorMessage: "",
      isPutOption: true,
      initRateETH2USD: 400,
      initVolatility: 0.8,
      periodSecBeforeMaturity: 14 * days,
      strikePrice: 1 / 380,
      erc20PriceE0: 1,
      decimal: 6,
      spread: 0,
      callOptionApproximation: 15.64268169 / 380 / 400,
      callOptionApproximationAccuracy: 0.95,
    },
    {
      errorMessage: "",
      isPutOption: true,
      initRateETH2USD: 300,
      initVolatility: 0.8,
      periodSecBeforeMaturity: 14 * days,
      strikePrice: 1 / 400,
      erc20PriceE0: 1,
      decimal: 6,
      spread: 0,
      callOptionApproximation: 100.7054059552 / 400 / 300,
      callOptionApproximationAccuracy: 0.95,
    },
    {
      errorMessage: "",
      isPutOption: true,
      initRateETH2USD: 400,
      initVolatility: 0.8,
      periodSecBeforeMaturity: 14 * days,
      strikePrice: 1 / 400,
      erc20PriceE0: 0.1,
      decimal: 6,
      spread: 0,
      callOptionApproximation: 24.97661485 / 400 / 400,
      callOptionApproximationAccuracy: 0.95,
    },
    // {
    //     errorMessage: '',
    //     isPutOption: true,
    //     initRateETH2USD: 1 / 400,
    //     initVolatility: 0.8,
    //     periodSecBeforeMaturity: 14 * days,
    //     strikePrice: 1 / 300,
    //     erc20PriceE0: 1,
    //     decimal: 6,
    //     spread: 0,
    //     callOptionApproximation: 0.7 / 300 / 400,
    //     callOptionApproximationAccuracy: -3.1,
    // },
  ],
};

export default testCases;
